import { Platform, StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
  },
  scrollView: {
    flex: 1,
    maxHeight: "100vh",
  },
  modalContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: 20
  },
  buttonContainer: {
    flexDirection: 'row',
  },
  button: {
    paddingVertical: 10,
    paddingHorizontal: 5,
    marginHorizontal: 2,
    marginVertical: 10,
    backgroundColor: '#d4d4d4',
    borderRadius: 5,
    alignItems: 'center',
    flex: 1,
  },
  selectedButton: {
    paddingVertical: 10,
    paddingHorizontal: 5,
    marginHorizontal: 2,
    marginVertical: 10,
    backgroundColor: '#1d4ed8',
    borderRadius: 5,
    alignItems: 'center',
    flex: 1,
  },
  buttonText: {
    fontSize: 14,
    fontWeight: 'semibold',
    color: '#000',
  },
  selectedButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  imageRow: {
    flexDirection: 'row',
    height: 120,
  },
  imageBox: {
    width: 100,
    height: 100,
    marginRight: 10,
    backgroundColor: '#f0f0f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addImageBox: {
    width: 100,
    height: 100,
    backgroundColor: '#f0f0f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  image: {
    width: 100,
    height: 100,
  },
  imageText: {
    fontSize: 12,
    textAlign: 'center',
  },
  infosEquipments: {
    flex: 1,
  },
  title: {
    textAlign: 'center',
    fontSize: 18,
    fontWeight: 'bold'
  },
  checklistItem: {
    marginBottom: 20,
    padding: 10,
    borderRadius: 5,
  },
  commentText: {
    marginTop: 5,
    fontStyle: 'italic',
    color: 'gray',
  },
  commentModalContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  commentInput: {
    width: '90%',
    padding: 10,
    backgroundColor: '#d4d4d4',
    borderRadius: 8,
    fontSize: 16,
    textAlignVertical: 'top',
  },
  saveCommentButton: {
    marginTop: 10,
    paddingVertical: 10,
    paddingHorizontal: 50,
    backgroundColor: '#007bff',
    borderRadius: 8,
  },
  itemActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  saveCommentButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  buttonFunctionsInModal: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    backgroundColor: '#1d4ed8',
    paddingVertical: 15,
    borderRadius: 10,
    marginVertical: 10,
  },
  buttonSaveInspection: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    backgroundColor: '#1d4ed8',
    paddingVertical: 15,
    borderRadius: 10,
    marginVertical: 10,
    marginBottom: Platform.OS === "web" ? 120 : 0,
  },
  extraordinaryItemsContainer: {
    backgroundColor: '#e0f7fa',
    marginBottom: 15,
    padding: 10,
    borderRadius: 10,
  },
  extraordinaryItemsTitle: {
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 16,
  },
  extraordinaryItem: {
    borderBottomColor: '#d4d4d4',
    borderBottomWidth: 1,
    padding: 5
  },
  bodyOfEquipement: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  bodyOfEquipementTitleAddBody: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: "space-evenly",
    backgroundColor: '#1d4ed8',
    borderRadius: 10,
    paddingVertical: 5,
  },
  titleBodyOfEquipement: {
    color: '#fff',
    width: '90%',
    textAlign: 'center',
    fontWeight: 'bold',
    paddingLeft: 5,
    paddingVertical: 2,
  },
  inputDatePicker: {
    flex: 1,
    flexDirection: 'row',
    padding: 10,
    minWidth: '45%',
    borderRadius: 10,
    backgroundColor: '#1d4ed8',
  },
  textInput: {
    borderColor: 'gray',
    borderWidth: 1,
    marginBottom: 10,
    padding: 10,
    borderRadius: 5,
  },
  deviceItemContainer: {
    flexDirection: "row",
    padding: 10,
    backgroundColor: "#f9f9f9",
    borderRadius: 8,
    marginVertical: 5,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ddd",
  },
  deviceImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 10,
    resizeMode: "cover",
  },
  placeholderImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 10,
    backgroundColor: "#e0e0e0",
    justifyContent: "center",
    alignItems: "center",
  },
  placeholderText: {
    color: "#888",
    fontSize: 12,
  },
  deviceInfoContainer: {
    flex: 1,
    justifyContent: "center",
  },
  deviceTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },
  deviceText: {
    fontSize: 14,
    color: "#666",
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  modalView: {
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '80%',
    maxWidth: 300,
  },
  modalText: {
    fontSize: 16,
    marginBottom: 15,
    textAlign: 'center',
    color: '#333',
  },
  loadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    zIndex: 9999,
  },
  loadingContent: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    width: '80%',
    maxWidth: 300,
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    marginBottom: 15,
    textAlign: 'center',
    color: '#333',
  },
  loadingIndicator: {
    marginVertical: 15,
  },
  loadingAnimation: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
  },
  progressBarContainer: {
    width: '100%',
    height: 20,
    backgroundColor: '#f0f0f0',
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#ddd',
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#1d4ed8',
  },
});

export default styles;