const checklistItemsInspection = [
  { id: 1, label: 'Registro de Segurança' },
  { id: 2, label: 'Relatório de Inspeção Anterior' },
  { id: 3, label: 'Programação de Inspeções com Datas Limites' },
  { id: 4, label: 'Recomendações de Inspeções Anteriores Não Realizadas' },
  { id: 5, label: 'Plaqueta de Identificação do Fabricante do Equipamento' },
  { id: 6, label: 'Plaqueta de Identificação NR-13 do Equipamento' },
  { id: 7, label: 'Desenho da Plaqueta de Identificação' },
  { id: 8, label: 'Desenho do Conjunto Geral e de Detalhes' },
  { id: 9, label: 'Projeto de Instalação Geral e do Equipamento' },
  { id: 10, label: 'Integridade dos Suportes e Estruturas' },
  { id: 11, label: 'Plano de Solda (Fabricação)' },
  { id: 12, label: 'Mapa de Medição de Espessura por Ultra-som' },
  { id: 13, label: 'Inspeção de Vazamentos nas Tubulações' },
  { id: 14, label: 'Funcionamento das Válvulas de Alimentação' },
  { id: 15, label: 'Inspeção das Bombas e Filtros de Alimentação' },
  { id: 16, label: 'Funcionamento do Queimador e Sistema de Combustão' },
  { id: 17, label: 'Ajustes e Calibração dos Sistemas' },
  { id: 18, label: 'Calibração dos Manômetros e Outros Instrumentos de Medição' },
  { id: 19, label: 'Certificado de Calibração das Válvulas de Segurança' },
  { id: 20, label: 'Funcionamento dos Dispositivos de Controle e Segurança' },
  { id: 21, label: 'Inspeção e Teste da Válvula de Segurança' },
  { id: 22, label: 'Memória de Cálculo das PMTA das Partes e do Equipamento' },
  { id: 23, label: 'Condição das Juntas e Vedantes' },
  { id: 24, label: 'Funcionamento das Válvulas de Drenagem' },
  { id: 25, label: 'Condição dos Ventiladores e Sistema de Exaustão' },
  { id: 26, label: 'Eficiência dos Trocas de Calor e Condição dos Tubos' },
  { id: 27, label: 'Verificação de Corrosão ou Desgaste Interno' },
  { id: 28, label: 'Memória de Cálculo do Teste Hidrostático' },
  { id: 29, label: 'Laudo de Teste Hidrostático' },
  { id: 30, label: 'Inspeção Periódica (Interna, Externa, TH)' },
  { id: 31, label: 'Inspeção de Início de Operação' },
  { id: 32, label: 'Inspeção de Problema Operacional' },
  { id: 33, label: 'Inspeção de Alteração Operacional' },
  { id: 34, label: 'Inspeção de Alteração e Reparo' },
  { id: 35, label: 'Inspeção de Reconstituição de Prontuário' },
  { id: 36, label: 'Inspeção de Parada ou Retorno de Operação' },
  { id: 37, label: 'Funcionamento dos Equipamentos de Proteção (extintores, alarmes)' },
  { id: 38, label: 'Testes de Alarmes de Pressão e Temperatura: Conformidade e Eficiência' },
  { id: 39, label: 'Operador Qualificado para Operações (Categoria I e II)' },
  { id: 40, label: 'Registro de Treinamento dos Operadores' },
  { id: 41, label: 'Elaboração do Relatório de Inspeção Detalhado' },
  { id: 42, label: 'Planejamento e Execução de Ações Corretivas' }
];

export default checklistItemsInspection;