const checklistItemsNR13 = [
  { id: 1, label: '13.1.1 O objetivo desta Norma Regulamentadora - NR é estabelecer requisitos mínimos para a gestão da integridade estrutural de caldeiras, vasos de pressão, suas tubulações de interligação e tanques metálicos de armazenamento nos aspectos relacionados à instalação, inspeção, operação e manutenção, visando a segurança e saúde dos trabalhadores' },
  { id: 2, label: '13.1.2 O empregador é o responsável pela adoção das medidas determinadas nesta NR' },
  { id: 3, label: '13.1.3 O disposto no item anterior aplica-se também aos equipamentos pertencentes aterceiros, circunscritos ao estabelecimento do empregador.' },
  { id: 4, label: '13.3.1 As seguintes situações constituem condição de grave e iminente risco: a) operação de equipamentos abrangidos por esta NR sem os dispositivos de segurança; b) atraso na inspeção de segurança periódica de caldeiras; c) ausência ou bloqueio de dispositivos de segurança, sem a devida justificativa técnica;' },
  { id: 5, label: '13.1.4 Considera-se estabelecimento com Serviço Próprio de Inspeção de Equipamentos - SPIE aquele cujo empregador obtém, de forma voluntária, a certificação prevista no Anexo II desta NR.' },
  { id: 6, label: '13.4.1.1 Para os propósitos desta NR, as caldeiras devem ser categorizadas da seguinte forma: a) caldeiras da categoria A são aquelas cuja pressão de operação é igual ou superior a 1.960 kPa; b) caldeiras da categoria B são aquelas cuja pressão de operação seja superior a 60 kPa e inferior a 1.960 kPa.' },
  { id: 7, label: '13.2 Campo de aplicação' },
  { id: 8, label: '13.2.1 Esta NR deve ser aplicada aos seguintes equipamentos:' },
  { id: 9, label: '13.2.1 a) caldeiras com pressão de operação superior a 60 kPa (0,61 kgf/cm²);' },
  { id: 10, label: '13.2.1 b) vasos de pressão cujo produto P.V seja superior a 8 (oito), onde P é o módulo da pressão máxima de operação em kPa e V o seu volume interno em m³;' },
  { id: 11, label: '13.2.1 c) vasos de pressão que contenham fluidos da classe A, especificados na alínea “a” do subitem 13.5.1.1.1, independente do produto P.V;' },
  { id: 12, label: '13.2.1 d) recipientes móveis com P.V superior a oito, onde P é o módulo da pressão máxima de operação em kPa, ou com fluidos da classe A, especificados na alínea “a” do subitem 13.5.1.1.1;' },
  { id: 13, label: '13.2.1 e) tubulações que contenham fluidos de classe A ou B, conforme as alíneas “a” e “b” do subitem 13.5.1.1.1, ligadas a caldeiras ou vasos de pressão abrangidos por esta NR; e' },
  { id: 14, label: '13.2.1 f) tanques metálicos de armazenamento, com diâmetro externo maior do que três metros, capacidade nominal acima de vinte mil litros, e que contenham fluidos de classe A ou B, conforme as alíneas “a” e “b” do subitem 13.5.1.1.1 desta NR' },
  { id: 15, label: '13.2.2 Esta NR não se aplica aos seguintes equipamentos:' },
  { id: 16, label: '13.2.2 a) recipientes transportáveis, vasos de pressão destinados ao transporte de produtos, reservatórios portáteis de fluido comprimido e extintores de incêndio;' },
  { id: 17, label: '13.2.2 b) vasos de pressão destinados à ocupação humana;' },
  { id: 18, label: '13.2.2 c) vasos de pressão integrantes de sistemas auxiliares de pacote de máquinas;' },
  { id: 19, label: '13.2.2 d) dutos e seus componentes;' },
  { id: 20, label: '13.2.2 e) fornos, serpentinas para troca térmica e aquecedores de fluido térmico;' },
  { id: 21, label: '13.2.2 f) vasos de pressão com diâmetro interno inferior a cento e cinquenta milímetros independentemente da classe do fluido;' },
  { id: 22, label: '13.2.2 g) geradores de vapor não enquadrados em códigos de vasos de pressão ou caldeira;' },
  { id: 23, label: '13.2.2 h) tubos de sistemas de instrumentação;' },
  { id: 24, label: '13.2.2 i) tubulações de redes públicas de distribuição de gás;' },
  { id: 25, label: '13.2.2 j) vasos de pressão fabricados em Plástico Reforçado de Fibra de Vidro - PRFV, inclusive aqueles sujeitos à condição de vácuo;' },
  { id: 26, label: '13.2.2 k) caldeiras com volume inferior a cem litros;' },
  { id: 27, label: '13.2.2 l) tanques estruturais de embarcações, navios e plataformas marítimas de exploração e produção de petróleo;' },
  { id: 28, label: '13.2.2 m) vasos e acumuladores de equipamentos submarinos destinados à produção e exploração de petróleo;' },
  { id: 29, label: '13.2.2 n) tanques enterrados ou apoiados sobre pernas, sapatas, pedestais ou selas;' },
  { id: 30, label: '13.2.2 o) panelas de cocção;' },
  { id: 31, label: '13.2.2 p) acumuladores e blocos hidráulicos;' },
  { id: 32, label: '13.2.2 q) tubulações que operam com vapor, observado o disposto no subitem 13.6.2.6 desta NR;' },
  { id: 33, label: '13.2.2 r) trocador de calor de placas corrugadas gaxetadas e brasadas;' },
  { id: 34, label: '13.2.2 s) vasos de pressão sujeitos exclusivamente a condições de vácuo menor ou igual a 5 kPa, que não contenham fluidos de classe A.' },
  { id: 35, label: '13.2.3 O disposto no item 13.2.2 não exime o empregador do dever de inspecionar e executar a manutenção dos referidos equipamentos e de outros sistemas pressurizados que ofereçam riscos aos trabalhadores, acompanhadas ou executadas por um responsável técnico, e observadas as recomendações do fabricante, bem como o disposto em códigos ou normas aplicáveis.' },
  { id: 36, label: '13.3 Disposições gerais' },
  { id: 37, label: '13.3.1 As seguintes situações constituem condição de grave e iminente risco:' },
  { id: 38, label: '13.3.1 a) operação de equipamentos abrangidos por esta NR sem os dispositivos de segurança previstos nos subitens 13.4.1.2 “a”, 13.5.1.2 “a”, 13.6.1.2 e 13.7.2.1;' },
  { id: 39, label: '13.3.1 b) atraso na inspeção de segurança periódica de caldeiras;' },
  { id: 40, label: '13.3.1 c) ausência ou bloqueio de dispositivos de segurança, sem a devida justificativa técnica, baseada em códigos, normas ou procedimentos formais de operação do equipamento;' },
  { id: 41, label: '13.3.1 d) ausência ou indisponibilidade operacional de dispositivo de controle do nível de água na caldeira;' },
  { id: 42, label: '13.3.1 e) operação de equipamento enquadrado nesta NR, cujo relatório de inspeção ateste a sua inaptidão operacional;' },
  { id: 43, label: '13.3.1 f) operação de caldeira em desacordo com o disposto no item 13.4.3.3 desta NR.' },
  { id: 44, label: '13.3.1.1 Por motivo de força maior e com justificativa formal do empregador, acompanhada por análise técnica e respectivas medidas de contingência para mitigaçãodos riscos, elaborada por Profissional Legalmente Habilitado - PLH ou por grupo multidisciplinar por ele coordenado, pode ocorrer postergação de até seis meses do prazo previsto para a inspeção de segurança periódica dos equipamentos abrangidos por esta NR' },
  { id: 45, label: '13.3.1.1.1 O empregador deve comunicar ao sindicato dos trabalhadores da categoria predominante do estabelecimento a justificativa formal para postergação da inspeção de segurança periódica dos equipamentos abrangidos por esta NR. ' },
  { id: 46, label: '13.3.2 Para efeito desta NR, considera-se PLH aquele que tem competência legal para o exercício da profissão de engenheiro nas atividades referentes a projeto de construção, acompanhamento da operação e da manutenção, inspeção e supervisão de inspeção de caldeiras, vasos de pressão, tubulações e tanques metálicos de armazenamento, em conformidade com a regulamentação profissional vigente no País.' },
  { id: 47, label: '13.3.2.1 O PLH pode obter voluntariamente a certificação de suas competências profissionais por intermédio de um Organismo de Certificação de Pessoas - OPC acreditado pela Coordenação Geral de Acreditação do Instituto Nacional de Metrologia, Qualidade e Tecnologia - Cgcre/INMETRO, conforme estabelece o Anexo III desta NR.' },
  { id: 48, label: '13.3.3 A inspeção de segurança dos equipamentos abrangidos por esta NR deve ser executada sob a responsabilidade técnica de PLH.' },
  { id: 49, label: '13.3.4 A inspeção de segurança dos equipamentos abrangidos por esta NR deve ser respaldada por exames e testes, a critério técnico do PLH, observado o disposto em códigos ou normas aplicáveis.' },
  { id: 50, label: '13.3.4.1 Deve ser observado o histórico dos equipamentos quando existente.' },
  { id: 51, label: '13.3.4.2 Os exames e testes devem ser realizados em condições de segurança para os executantes e demais trabalhadores envolvidos.' },
  { id: 52, label: '13.3.4.3 A execução de testes pneumáticos ou hidropneumáticos, quando indispensável, deve ser realizada sob responsabilidade técnica de PLH, com aprovação prévia dos procedimentos a serem aplicados' },
  { id: 53, label: '13.3.5 É proibida a inibição dos instrumentos, controles e sistemas de segurança, exceto quando prevista, de forma provisória, em procedimentos formais de operação e manutenção ou mediante justificativa formalmente documentada elaborada por responsável técnico, com prévia análise de risco e anuência do empregador ou de preposto por ele designado, desde que mantida a segurança operacional.' },
  { id: 54, label: '13.3.6 Os instrumentos e sistemas de controle e segurança dos equipamentos abrangidos por esta NR devem ser mantidos em condições adequadas de uso e devidamente inspecionados e testados ou, quando aplicável, calibrados.' },
  { id: 55, label: '13.3.7 Todos os reparos ou alterações em equipamentos abrangidos nesta NR devem respeitar os respectivos códigos de construção e as prescrições do fabricante no que se refere a:' },
  { id: 56, label: '13.3.7 a) materiais;' },
  { id: 57, label: '13.3.7 b) procedimentos de execução;' },
  { id: 58, label: '13.3.7 c) procedimentos de controle de qualidade;' },
  { id: 59, label: '13.3.7 d) qualificação e certificação de pessoal.' },
  { id: 60, label: '13.3.7.1 Quando não for conhecido o código de construção, deve ser respeitada a concepção original da caldeira, vaso de pressão, tubulação ou tanque metálico de armazenamento, empregando-se os procedimentos de controle prescritos pelos códigos aplicáveis a esses equipamentos.' },
  { id: 61, label: '13.3.7.2 A critério técnico do PLH, podem ser utilizadas tecnologias de cálculo ou procedimentos mais avançados, em substituição aos previstos pelos códigos de construção.' },
  { id: 62, label: '13.3.7.3 Projetos de alteração ou reparo devem ser concebidos previamente nas seguintes situações:' },
  { id: 63, label: '13.3.7.3 a) sempre que as condições de projeto forem modificadas;' },
  { id: 64, label: '13.3.7.3 b) sempre que forem realizados reparos que possam comprometer a segurança.' },
  { id: 65, label: '13.3.7.4 Os projetos de alteração e os projetos de reparo devem:' },
  { id: 66, label: '13.3.7.4 a) ser concebidos ou aprovados por PLH;' },
  { id: 67, label: '13.3.7.4 b) determinar materiais, procedimentos de execução, controle de qualidade e qualificação de pessoal;' },
  { id: 68, label: '13.3.7.4 c) ser divulgados para os empregados do estabelecimento que estão envolvidos com o equipamento.' },
  { id: 69, label: '13.3.7.5 Todas as intervenções que exijam mandrilamento ou soldagem em partes que operem sob pressão devem ser objeto de exames ou testes para controle da qualidade com parâmetros definidos por PLH, de acordo com códigos ou normas aplicáveis.' },
  { id: 70, label: '13.3.8 Os relatórios de inspeção de segurança dos equipamentos abrangidos por esta NR devem ser elaborados em até 60 (sessenta) dias ou, no caso de parada geral de manutenção, em até 90 (noventa) dias.' },
  { id: 71, label: '13.3.8.1 Imediatamente após a inspeção de segurança de caldeira, vaso de pressão ou tanque metálico de armazenamento, deve ser anotada, no respectivo registro de segurança, previsto nos subitens 13.4.1.8, 13.5.1.7 e 13.7.1.3 desta NR, a condição operacional e de segurança.' },
  { id: 72, label: '13.3.8.2 As recomendações decorrentes das inspeções de segurança devem ser registradas e implementadas pelo empregador, com a determinação de prazos e responsáveis pela execução.' },
  { id: 73, label: '13.3.9 Os relatórios, projetos, certificados e demais documentos previstos nesta NR podem ser elaborados e armazenados em sistemas informatizados, com segurança da informação, ou mantidos em mídia eletrônica com assinatura validada por uma Autoridade Certificadora - AC, assegurados os requisitos de autenticidade, integridade, disponibilidade, rastreabilidade e irretratabilidade das informações.' },
  { id: 74, label: '13.3.9.1 No caso de versão impressa de relatórios de inspeção de segurança, as páginas devem ser numeradas' },
  { id: 75, label: '13.3.10 A documentação dos equipamentos abrangidos por esta NR deve permanecer à disposição para consulta dos operadores, do pessoal de manutenção, de inspeção e das representações dos trabalhadores e do empregador na Comissão Interna de Prevenção de Acidentes - CIPA, devendo o empregador assegurar pleno acesso a essa documentação, inclusive à representação sindical da categoria profissional predominante do estabelecimento, quando formalmente solicitado.' },
  { id: 76, label: '13.3.11 O empregador deve comunicar à autoridade regional competente em matéria de trabalho e ao sindicato da categoria profissional predominante do estabelecimento a ocorrência de vazamento, incêndio ou explosão envolvendo equipamentos abrangidos por esta NR que tenha como consequência uma das situações a seguir:' },
  { id: 77, label: '13.3.11 a) morte de trabalhador(es);' },
  { id: 78, label: '13.3.11 b) internação hospitalar de trabalhador(es);' },
  { id: 79, label: '13.3.11 c) eventos de grande proporção.' },
  { id: 80, label: '13.3.11.1 A comunicação deve ser encaminhada até o segundo dia útil após a ocorrência e deve conter:' },
  { id: 81, label: '13.3.11.1 a) razão social do empregador, endereço, local, data e hora da ocorrência;' },
  { id: 82, label: '13.3.11.1 b) descrição da ocorrência;' },
  { id: 83, label: '13.3.11.1 c) nome e função da(s) vítima(s);' },
  { id: 84, label: '13.3.11.1 d) procedimentos de investigação adotados;' },
  { id: 85, label: '13.3.11.1 e) cópia do último relatório de inspeção de segurança do equipamento envolvido;' },
  { id: 86, label: '13.3.11.1 f) cópia da Comunicação de Acidente de Trabalho - CAT.' },
  { id: 87, label: '13.3.11.2 Na ocorrência de acidentes previstos no subitem 13.3.11, o empregador deve comunicar formalmente a representação sindical dos trabalhadores predominante do estabelecimento para participar da respectiva investigação.' },
  { id: 88, label: '13.3.12 As caldeiras e vasos de pressão comprovadamente fabricados em série devem ser certificados no âmbito do Sistema Brasileiro de Avaliação de Conformidade, quandoaplicável.' },
  { id: 89, label: '13.3.13 É proibida a construção, importação, comercialização, leilão, locação, cessão a qualquer título, exposição e utilização de caldeiras e vasos de pressão sem a indicação do respectivo código de construção no prontuário e na placa de identificação.' },
  { id: 90, label: '13.4 Caldeiras' },
  { id: 91, label: '13.4.1 Disposições Gerais' },
  { id: 92, label: '13.4.1.1 Para os propósitos desta NR, as caldeiras devem ser categorizadas da seguinte forma:' },
  { id: 93, label: '13.4.1.1 a) caldeiras da categoria A são aquelas cuja pressão de operação é igual ou superior a 1.960 kPa (19,98 kgf/cm²); ' },
  { id: 94, label: '13.4.1.1 b) caldeiras da categoria B são aquelas cuja pressão de operação seja superior a 60 kPa (0,61 kgf/cm²) e inferior a 1 960 kPa (19,98 kgf/cm2).' },
  { id: 95, label: '13.4.1.2 As caldeiras devem ser dotadas dos seguintes itens:' },
  { id: 96, label: '13.4.1.2 a) válvula de segurança com pressão de abertura ajustada em valor igual ou inferior à Pressão Máxima de Trabalho Admissível - PMTA, respeitados os requisitos do código de construção relativos a aberturas escalonadas e tolerâncias de pressão de ajuste;' },
  { id: 97, label: '13.4.1.2 b) instrumento que indique a pressão do vapor acumulado;' },
  { id: 98, label: '13.4.1.2 c) injetor ou sistema de alimentação de água independente do principal, nas caldeiras de combustível sólido não atomizado ou com queima em suspensão;' },
  { id: 99, label: '13.4.1.2 d) sistema dedicado de drenagem rápida de água em caldeiras de recuperação de álcalis, com ações automáticas após acionamento pelo operador;' },
  { id: 100, label: '13.4.1.2 e) sistema automático de controle do nível de água com intertravamento que evite o superaquecimento por alimentação deficiente.' },
  { id: 101, label: '13.4.1.3 Toda caldeira deve ter afixada em seu corpo, em local de fácil acesso e visível, placa de identificação indelével com, no mínimo, as seguintes informações:' },
  { id: 102, label: '13.4.1.3 a) nome do fabricante;' },
  { id: 103, label: '13.4.1.3 b) número de ordem dado pelo fabricante da caldeira;' },
  { id: 104, label: '13.4.1.3 c) ano de fabricação;' },
  { id: 105, label: '13.4.1.3 d) pressão máxima de trabalho admissível;' },
  { id: 106, label: '13.4.1.3 e) capacidade de produção de vapor;' },
  { id: 107, label: '13.4.1.3 f) área de superfície de aquecimento;' },
  { id: 108, label: '13.4.1.3 g) código de construção e ano de edição.' },
  { id: 109, label: '13.4.1.4 Além da placa de identificação, deve constar, em local visível, a categoria da caldeira e seu número ou código de identificação.' },
  { id: 110, label: '13.4.1.5 Toda caldeira deve possuir, no estabelecimento onde estiver instalada, a seguinte documentação devidamente atualizada:' },
  { id: 111, label: '13.4.1.5 a) prontuário da caldeira, fornecido por seu fabricante, contendo as seguintes informações:' },
  { id: 112, label: '13.4.1.5 a) I - código de construção e ano de edição;' },
  { id: 113, label: '13.4.1.5 a) II - especificação dos materiais;' },
  { id: 114, label: '13.4.1.5 a) III - procedimentos utilizados na fabricação, montagem e inspeção final;' },
  { id: 115, label: '13.4.1.5 a) IV - metodologia para estabelecimento da PMTA;' },
  { id: 116, label: '13.4.1.5 a) V - registros da execução do teste hidrostático de fabricação;' },
  { id: 117, label: '13.4.1.5 a) VI - conjunto de desenhos e demais dados necessários ao monitoramento da vida útil da caldeira;' },
  { id: 118, label: '13.4.1.5 a) VII - características funcionais;' },
  { id: 119, label: '13.4.1.5 a) VIII - dados dos dispositivos de segurança;' },
  { id: 120, label: '13.4.1.5 a) IX - ano de fabricação;' },
  { id: 121, label: '13.4.1.5 a) X - categoria da caldeira;' },
  { id: 122, label: '13.4.1.5 b) registro de segurança;' },
  { id: 123, label: '13.4.1.5 c) projeto de instalação;' },
  { id: 124, label: '13.4.1.5 d) projeto de alteração ou reparo;' },
  { id: 125, label: '13.4.1.5 e) relatórios de inspeção de segurança;' },
  { id: 126, label: '13.4.1.5 f) certificados de inspeção e teste dos dispositivos de segurança.' },
  { id: 127, label: '13.4.1.6 Quando inexistente ou extraviado, o prontuário da caldeira deve ser reconstituído pelo empregador, com responsabilidade técnica do fabricante ou de PLH, sendo imprescindível a reconstituição das características funcionais, dos dados dos dispositivos de segurança e da memória de cálculo da PMTA.' },
  { id: 128, label: '13.4.1.7 Quando a caldeira for vendida ou transferida de estabelecimento, os documentos mencionados nas alíneas “a”, “d”, e “e” do subitem 13.4.1.5 devem acompanhá-la.' },
  { id: 129, label: '13.4.1.8 O registro de segurança deve ser constituído por livro de páginas numeradas, pastas ou sistema informatizado onde serão registradas:' },
  { id: 130, label: '13.4.1.8 a) todas as ocorrências importantes capazes de influir nas condições de segurança da caldeira, inclusive alterações nos prazos de inspeção;' },
  { id: 131, label: '13.4.1.8 b) as ocorrências de inspeções de segurança inicial, periódica e extraordinária, devendo constar a condição operacional da caldeira, o nome legív' },
  { id: 132, label: '13.4.1.9 Caso a caldeira venha a ser considerada inadequada para uso, o registro de segurança deve conter tal informação e receber encerramento formal.' },
  { id: 133, label: '13.4.2 Instalação de caldeiras' },
  { id: 134, label: '13.4.2.1 A autoria do projeto de instalação de caldeiras é de responsabilidade de PLH, e deve obedecer aos aspectos de segurança, saúde e meio ambiente previstos nas normasregulamentadoras, convenções e disposições legais aplicáveis.' },
  { id: 135, label: '13.4.2.2 As caldeiras de qualquer estabelecimento devem ser instaladas em local específico para tal fim, denominado casa de caldeiras ou área de caldeiras.' },
  { id: 136, label: '13.4.2.3 Quando a caldeira for instalada em ambiente aberto, a área de caldeiras deve satisfazer os seguintes requisitos:' },
  { id: 137, label: '13.4.2.3 a) estar afastada, no mínimo, três metros de outras instalações do estabelecimento, dos depósitos de combustíveis, excetuando-se reservatórios para partida com até dois mil litros de capacidade, do limite de propriedade de terceiros e do limite com as vias públicas;' },
  { id: 138, label: '13.4.2.3 b) dispor de pelo menos duas saídas amplas, permanentemente desobstruídas, sinalizadas e dispostas em direções distintas;' },
  { id: 139, label: '13.4.2.3 c) dispor de acesso fácil e seguro, necessário à operação e à manutenção da caldeira, sendo que, para guarda-corpos vazados, os vãos devem ter dimensões que impeçam a queda de pessoas;' },
  { id: 140, label: '13.4.2.3 d) ter sistema de captação e lançamento dos gases e material particulado, provenientes da combustão, para fora da área de operação, atendendo às normas ambientais vigentes;' },
  { id: 141, label: '13.4.2.3 e) dispor de iluminação conforme normas oficiais vigentes;' },
  { id: 142, label: '13.4.2.3 f) ter sistema de iluminação de emergência caso opere à noite.' },
  { id: 143, label: '13.4.2.4 Quando a caldeira estiver instalada em ambiente fechado, a casa de caldeiras deve satisfazer os seguintes requisitos:' },
  { id: 144, label: '13.4.2.4 a) constituir prédio separado, construído de material resistente ao fogo, podendo ter apenas uma parede adjacente a outras instalações do estabelecimento, porém com as outras paredes afastadas de, no mínimo, três metros de outras instalações, do limite de propriedade de terceiros, do limite com as vias públicas e de depósitos de combustíveis, excetuando-se reservatórios para partida com até dois mil litros de capacidade;' },
  { id: 145, label: '13.4.2.4 b) dispor de pelo menos duas saídas amplas, permanentemente desobstruídas, sinalizadas e dispostas em direções distintas;' },
  { id: 146, label: '13.4.2.4 c) dispor de ventilação permanente com entradas de ar que não possam ser bloqueadas;' },
  { id: 147, label: '13.4.2.4 d) dispor de sensor para detecção de vazamento de gás, quando se tratar de caldeira a combustível gasoso;' },
  { id: 148, label: '13.4.2.4 e) não ser utilizada para qualquer outra finalidade;' },
  { id: 149, label: '13.4.2.4 f) dispor de acesso fácil e seguro, necessário à operação e à manutenção da caldeira,sendo que, para guarda-corpos vazados, os vãos devem ter dimensões que impeçam a queda de pessoas;' },
  { id: 150, label: '13.4.2.4 g) ter sistema de captação e lançamento dos gases e material particulado, provenientes da combustão, para fora da área de operação, atendendo às normas ambientais vigentes; ' },
  { id: 151, label: '13.4.2.4 h) dispor de iluminação conforme normas oficiais vigentes e ter sistema de iluminação de emergência' },
  { id: 152, label: '13.4.2.5 Quando o estabelecimento não puder atender ao disposto nos subitens 13.4.2.3 e 13.4.2.4, deve ser elaborado projeto alternativo de instalação, com medidas complementares de segurança que permitam a atenuação dos riscos, comunicando previamente à representação sindical da categoria profissional predominante do estabelecimento.' },
  { id: 153, label: '13.4.2.6 As caldeiras classificadas na categoria A devem possuir painel de instrumentos instalados em sala de controle, construída segundo o que estabelecem as normas regulamentadoras aplicáveis.' },
  { id: 154, label: '13.4.3 Segurança na operação de caldeiras' },
  { id: 155, label: '13.4.3.1 Toda caldeira deve possuir manual de operação atualizado, em língua portuguesa, em local de fácil acesso aos operadores, contendo no mínimo:' },
  { id: 156, label: '13.4.3.1 a) procedimentos de partidas e paradas;' },
  { id: 157, label: '13.4.3.1 b) procedimentos e parâmetros operacionais de rotina;' },
  { id: 158, label: '13.4.3.1 c) procedimentos para situações de emergência;' },
  { id: 159, label: '13.4.3.1 d) procedimentos gerais de segurança, de saúde e de preservação do meio ambiente.' },
  { id: 160, label: '13.4.3.2 A qualidade da água deve ser controlada e tratamentos devem ser implementados, quando necessários, para compatibilizar suas propriedades físicoquímicas com os parâmetros de operação da caldeira definidos pelo fabricante.' },
  { id: 161, label: '13.4.3.3 Toda caldeira deve estar, obrigatoriamente, sob operação e controle de operador de caldeira.' },
  { id: 162, label: '13.4.3.4 É considerado operador de caldeira aquele que cumprir o disposto no item 1.1 do Anexo I desta NR.' },
  { id: 163, label: '13.4.4 Inspeção de segurança de caldeiras' },
  { id: 164, label: '13.4.4.1 As caldeiras devem ser submetidas a inspeções de segurança inicial, periódica e extraordinária.' },
  { id: 165, label: '13.4.4.2 A inspeção de segurança inicial deve ser feita em caldeiras novas, antes da entrada em funcionamento, no local definitivo de instalação, devendo compreender exame interno, externo e teste de pressão.' },
  { id: 166, label: '13.4.4.3 As caldeiras devem, obrigatoriamente, ser submetidas a Teste Hidrostático - TH em sua fase de fabricação, com comprovação por meio de laudo assinado por PLH.' },
  { id: 167, label: '13.4.4.3.1 Na falta de comprovação documental de que o TH tenha sido realizado na fase de fabricação, se aplicará o disposto a seguir:' },
  { id: 168, label: '13.4.4.3.1 a) para as caldeiras fabricadas ou importadas a partir de 2 de maio de 2014, o TH correspondente ao da fase de fabricação deve ser feito durante a inspeção de segurança inicial;' },
  { id: 169, label: '13.4.4.3.1 b) para as caldeiras em operação antes de 2 de maio de 2014, a execução do TH correspondente ao da fase de fabricação fica a critério técnico do PLH e, caso este julgue necessário, deve ser executado até a próxima inspeção de segurança periódica interna.' },
  { id: 170, label: '13.4.4.4 A inspeção de segurança periódica, constituída por exames interno e externo, deve ser executada nos seguintes prazos máximos:' },
  { id: 171, label: '13.4.4.4 a) doze meses para caldeiras das categorias A e B;' },
  { id: 172, label: '13.4.4.4 b) dezoito meses para caldeiras de recuperação de álcalis de qualquer categoria;' },
  { id: 173, label: '13.4.4.4 c) vinte e quatro meses para caldeiras da categoria A, desde que aos doze meses sejam testadas as pressões de abertura das válvulas de segurança;' },
  { id: 174, label: '13.4.4.4 d) trinta meses para caldeiras de categoria B com sistema de gerenciamento de combustão - SGC que atendam ao disposto no Anexo IV desta NR.' },
  { id: 175, label: '13.4.4.5 Estabelecimentos que possuam SPIE, conforme estabelecido no Anexo II, podem estender os períodos entre inspeções de segurança, respeitando os seguintes prazos máximos:' },
  { id: 176, label: '13.4.4.5 a) vinte e quatro meses para as caldeiras de recuperação de álcalis;' },
  { id: 177, label: '13.4.4.5 b) vinte e quatro meses para as caldeiras da categoria B;' },
  { id: 178, label: '13.4.4.5 c) trinta meses para caldeiras da categoria A;' },
  { id: 179, label: '13.4.4.5 d) quarenta e oito meses para caldeiras de categoria A com Sistema Instrumentado de Segurança - SIS, que atendam ao disposto no Anexo IV desta NR.' },
  { id: 180, label: '13.4.4.6 No máximo, ao completar vinte e cinco anos de uso, na sua inspeção subsequente, as caldeiras devem ser submetidas a uma avaliação de integridade com maior abrangência, de acordo com códigos ou normas aplicáveis, para determinar a sua vida remanescente e novos prazos máximos para inspeção, caso ainda estejam em condições de uso.' },
  { id: 181, label: '13.4.4.7 As válvulas de segurança de caldeiras devem ser desmontadas, inspecionadas e testadas com prazo adequado à sua manutenção, porém, não superior ao previsto para a inspeção de segurança periódica das caldeiras por elas protegidas, de acordo com os subitens 13.4.4.4 e 13.4.4.5.' },
  { id: 182, label: '13.4.4.7.1 Em situações excepcionais, devidamente justificadas por PLH, as válvulas de segurança que não atendam ao disposto no subitem 13.4.4.7 podem ser testadas no campo, com uma frequência compatível com o histórico operacional destes dispositivos.' },
  { id: 183, label: '13.4.4.8 Além do disposto no subitem 13.4.4.7, as válvulas de segurança instaladas em caldeiras de categoria B devem ser testadas periodicamente conforme segue:' },
  { id: 184, label: '13.4.4.8 a) pelo menos uma vez por mês, mediante acionamento manual da alavanca durante a operação de caldeiras sem tratamento de água, exceto para aquelas que vaporizem fluido térmico;' },
  { id: 185, label: '13.4.4.8 b) as caldeiras que operem com água tratada devem ter a alavanca acionada manualmente, de acordo com as prescrições do fabricante.' },
  { id: 186, label: '13.4.4.9 Adicionalmente aos testes prescritos nos subitens 13.4.4.7 e 13.4.4.8, as válvulas de segurança instaladas em caldeiras podem ser submetidas a testes de acumulação, a critério técnico do PLH.' },
  { id: 187, label: '13.4.4.10 A inspeção de segurança extraordinária deve ser feita nas seguintes oportunidades:' },
  { id: 188, label: '13.4.4.10 a) sempre que a caldeira for danificada por acidente ou outra ocorrência capaz de comprometer sua segurança;' },
  { id: 189, label: '13.4.4.10 b) quando a caldeira for submetida a alteração ou reparo importante capaz de alterar suas condições de segurança;' },
  { id: 190, label: '13.4.4.10 c) antes de a caldeira ser recolocada em funcionamento, quando permanecer inativa por mais de seis meses;' },
  { id: 191, label: '13.4.4.10 d) quando houver mudança de local de instalação da caldeira.' },
  { id: 192, label: '13.4.4.11 O empregador deve informar à representação sindical da categoria profissional predominante do estabelecimento, quando demandado formalmente, num prazo máximo de 30 (trinta) dias após o término da inspeção de segurança periódica, a condição operacional da caldeira.' },
  { id: 193, label: '13.4.4.11.1 Mediante o recebimento de requisição formal, o empregador deve encaminhar à representação sindical da categoria profissional predominante do estabelecimento, no prazo máximo de 10 (dez) dias após a sua elaboração, a cópia do relatório de inspeção.' },
  { id: 194, label: '13.4.4.11.2 A representação sindical da categoria profissional predominante do estabelecimento pode solicitar ao empregador que seja enviada, de maneira regular, cópia do relatório de inspeção de segurança da caldeira, no prazo de trinta dias após a sua elaboração, ficando o empregador desobrigado de atender ao contido nos subitens 13.4.4.11 e 13.4.4.11.1.' },
  { id: 195, label: '13.4.4.12 O relatório de inspeção de segurança, mencionado na alínea “e” do subitem 13.4.1.5, deve conter no mínimo:' },
  { id: 196, label: '13.4.4.12 a) dados constantes na placa de identificação da caldeira;' },
  { id: 197, label: '13.4.4.12 b) categoria da caldeira;' },
  { id: 198, label: '13.4.4.12 c) tipo da caldeira;' },
  { id: 199, label: '13.4.4.12 d) tipo de inspeção executada;' },
  { id: 200, label: '13.4.4.12 e) data de início e término da inspeção;' },
  { id: 201, label: '13.4.4.12 f) descrição das inspeções, exames e testes executados;' },
  { id: 202, label: '13.4.4.12 g) registros fotográficos do exame interno da caldeira;' },
  { id: 203, label: '13.4.4.12 h) resultado das inspeções e intervenções executadas;' },
  { id: 204, label: '13.4.4.12 i) relação dos itens desta NR, relativos a caldeiras, que não estão sendo atendidos;' },
  { id: 205, label: '13.4.4.12 j) recomendações e providências necessárias;' },
  { id: 206, label: '13.4.4.12 k) parecer conclusivo quanto à integridade da caldeira até a próxima inspeção;' },
  { id: 207, label: '13.4.4.12 l) data prevista para a próxima inspeção de segurança da caldeira;' },
  { id: 208, label: '13.4.4.12 m)nome legível, assinatura e número do registro no conselho profissional do PLH e nome legível e assinatura de técnicos que participaram da inspeção;' },
  { id: 209, label: '13.4.4.12 n) número do certificado de inspeção e teste da válvula de segurança.' },
  { id: 210, label: '13.4.4.13 Sempre que os resultados da inspeção determinarem alterações dos dados de projeto, a placa de identificação e a documentação do prontuário devem ser atualizadas.' },
  { id: 211, label: '13.5 Vasos de pressão' },
  { id: 212, label: '13.5.1 Disposições Gerais ' },
  { id: 213, label: '13.5.1.1 Para os efeitos desta NR, os vasos de pressão devem ser categorizados, com base na classe do fluido e no grupo de potencial de risco, mediante a aplicação da Tabela 1.' },
  { id: 214, label: '13.5.1.1.1 Os fluidos contidos nos vasos de pressão devem ser classificados conforme descrito a seguir: ' },
  { id: 215, label: '13.5.1.1.1 a) classe A: I - fluidos inflamáveis; II - fluidos combustíveis com temperatura superior ou igual a duzentos graus Celsius (200 ºC); III - fluidos tóxicos com limite de tolerância igual ou inferior a vinte partes por milhão (20 ppm); IV - hidrogênio; V - acetileno.' },
  { id: 216, label: '13.5.1.1.1 b) classe B: I - fluidos combustíveis com temperatura inferior a duzentos graus Celsius (200 ºC); II - fluidos tóxicos com limite de tolerância superior a vinte partes por milhão (20 ppm). ' },
  { id: 217, label: '13.5.1.1.1 c) classe C: I - vapor de água; II - gases asfixiantes simples; III - ar comprimido. ' },
  { id: 218, label: '13.5.1.1.1 d) classe D: I - outros fluidos não enquadrados nas classes anteriores.' },
  { id: 219, label: '13.5.1.1.2 Quando se tratar de mistura, deve ser considerado, para fins de classificação, o fluido que apresentar maior risco aos trabalhadores e às instalações, considerando-se sua toxicidade, inflamabilidade e concentração.' },
  { id: 220, label: '13.5.1.1.3 O grupo de potencial de risco do vaso de pressão deve ser estabelecido a partir do produto P.V, onde P é a pressão máxima de operação em MPa, em módulo, e V o seu volume em m³ (metro cúbico), conforme segue: ' },
  { id: 221, label: '13.5.1.1.3 a) Grupo 1 - P.V > 100;' },
  { id: 222, label: '13.5.1.1.3 b) Grupo 2 - P.V < 100 e P.V > 30;' },
  { id: 223, label: '13.5.1.1.3 c) Grupo 3 - P.V < 30 e P.V > 2,5;' },
  { id: 224, label: '13.5.1.1.3 d) Grupo 4 - P.V < 2,5 e P.V > 1;' },
  { id: 225, label: '13.5.1.1.3 e) Grupo 5 - P.V < 1.' },
  { id: 226, label: '13.5.1.2 Os vasos de pressão devem ser dotados dos seguintes itens:' },
  { id: 227, label: '13.5.1.2 a) válvula de segurança ou outro dispositivo de segurança com pressão de abertura ajustada em valor igual ou inferior à PMTA, instalado diretamente no vaso ou no sistema que o inclui, considerados os requisitos do código de construção relativos a aberturas escalonadas e tolerâncias de pressão de ajuste;' },
  { id: 228, label: '13.5.1.2 b) vasos de pressão submetidos a vácuo devem ser dotados de dispositivos de segurança ou outros meios previstos no projeto; ' },
  { id: 229, label: '13.5.1.2 c) medidas para evitar o bloqueio inadvertido de dispositivos de segurança, incluindo controles administrativos ou, quando inexistentes, utilização de Dispositivo Contra Bloqueio Inadvertido - DCBI associado à sinalização de advertência; ' },
  { id: 230, label: '13.5.1.2 d) instrumento que indique a pressão de operação, instalado diretamente no vaso ou no sistema que o contenha. ' },
  { id: 231, label: '13.5.1.2.1 Os sistemas intrinsicamente protegidos, concebidos e mantidos em conformidade com o respectivo código de construção, podem prescindir do disposto no subitem 13.5.1.2, alínea “a” ou “b”, mediante parecer técnico emitido por PLH. ' },
  { id: 232, label: '13.5.1.3 Todo vaso de pressão deve ter afixado em seu corpo, em local de fácil acesso e visível, placa de identificação indelével com, no mínimo, as seguintes informações: ' },
  { id: 233, label: '13.5.1.3 a) fabricante;' },
  { id: 234, label: '13.5.1.3 b) número de identificação;' },
  { id: 235, label: '13.5.1.3 c) ano de fabricação;' },
  { id: 236, label: '13.5.1.3 d) pressão máxima de trabalho admissível; ' },
  { id: 237, label: '13.5.1.3 e) código de construção e ano de edição.' },
  { id: 238, label: '13.5.1.4 Além da placa de identificação, devem constar, em local visível, a categoria do vaso e seu número ou código de identificação.' },
  { id: 239, label: '13.5.1.5 Todo vaso de pressão deve possuir, no estabelecimento onde estiver instalado, a seguinte documentação devidamente atualizada:' },
  { id: 240, label: '13.5.1.5 a) I - código de construção e ano de edição; ' },
  { id: 241, label: '13.5.1.5 a) II - especificação dos materiais;' },
  { id: 242, label: '13.5.1.5 a) III - procedimentos utilizados na fabricação, montagem e inspeção final;' },
  { id: 243, label: '13.5.1.5 a) IV - metodologia para estabelecimento da PMTA; ' },
  { id: 244, label: '13.5.1.5 a) V - conjunto de desenhos e demais dados necessários ao monitoramento da sua vida útil;' },
  { id: 245, label: '13.5.1.5 a) VI - pressão máxima de operação;' },
  { id: 246, label: '13.5.1.5 a) VII - registros da execução do teste hidrostático de fabricação;' },
  { id: 247, label: '13.5.1.5 a) VIII - características funcionais; ' },
  { id: 248, label: '13.5.1.5 a) IX - dados dos dispositivos de segurança; ' },
  { id: 249, label: '13.5.1.5 a) X - ano de fabricação;' },
  { id: 250, label: '13.5.1.5 a) XI - categoria do vaso;' },
  { id: 251, label: '13.5.1.5 b) registro de segurança;' },
  { id: 252, label: '13.5.1.5 c) projeto de alteração ou reparo;' },
  { id: 253, label: '13.5.1.5 d) relatórios de inspeção de segurança;' },
  { id: 254, label: '13.5.1.5 e) certificados de inspeção e teste dos dispositivos de segurança.' },
  { id: 255, label: '13.5.1.6 Quando inexistente ou extraviado, o prontuário do vaso de pressão deve ser reconstituído pelo empregador, com responsabilidade técnica do fabricante ou de PLH, sendo imprescindível a reconstituição das premissas de projeto, dos dados dos dispositivos de segurança e da memória de cálculo da PMTA. ' },
  { id: 256, label: '13.5.1.6.1 Vasos de pressão construídos sem códigos de construção, instalados antes da publicação da Portaria MTb nº 1.082, de 18 de dezembro de 2018, D.O.U de 20/12/2018, para os quais não seja possível a reconstituição da memória de cálculo por códigos reconhecidos, devem ter PMTA atribuída por PLH, a partir dos dados operacionais e serem submetidos a inspeções periódicas, conforme os prazos abaixo:' },
  { id: 257, label: '13.5.1.6.1 a) um ano, para inspeção de segurança periódica externa;' },
  { id: 258, label: '13.5.1.6.1 b) três anos, para inspeção de segurança periódica interna.'},
  { id: 259, label: '13.5.1.6.2 A empresa deve elaborar um plano de ação para realização de inspeção extraordinária especial de todos os vasos relacionados no subitem 13.5.1.6.1.' },
  { id: 260, label: '13.5.1.6.3 O prazo para implementação do projeto de alteração ou de reparo não deve ser superior à vida remanescente calculada quando da execução da inspeção extraordinária especial.' },
  { id: 261, label: '13.5.1.7 O registro de segurança deve ser constituído por livro de páginas numeradas, pastas ou sistema informatizado onde serão registradas: ' },
  { id: 262, label: '13.5.1.7 a) todas as ocorrências importantes capazes de influir nas condições de segurança dos vasos de pressão, inclusive alterações nos prazos de inspeção;' },
  { id: 263, label: '13.5.1.7 b) as ocorrências de inspeções de segurança inicial, periódica e extraordinária, devendo constar a condição operacional do vaso, o nome legível e assinatura do PLH. ' },
  { id: 264, label: '13.5.1.7.1 O empregador deve fornecer cópias impressas ou em mídia eletrônica das páginas dos registros de segurança selecionadas pela representação sindical da categoria profissional predominante do estabelecimento, quando formalmente solicitadas. ' },
  { id: 265, label: '13.5.2 Instalação de vasos de pressão.' },
  { id: 266, label: '13.5.2.1 Todo vaso de pressão deve ser instalado de modo que todos os drenos, respiros, bocas de visita e indicadores de nível, pressão e temperatura, quando acessados por meio seguros. ' },
  { id: 267, label: '13.5.2.2 Quando os vasos de pressão forem instalados em ambientes fechados, a instalação deve satisfazer os seguintes requisitos: ' },
  { id: 268, label: '13.5.2.2 a) pelo menos duas saídas amplas, permanentemente desobstruídas, sinalizadas e dispostas em direções distintas; ' },
  { id: 269, label: '13.5.2.2 b) acesso fácil e seguro para as atividades de manutenção, operação e inspeção, sendo que, para guarda-corpos vazados, os vãos devem ter dimensões que impeçam a queda de pessoas; ' },
  { id: 270, label: '13.5.2.2 c) ventilação permanente com entradas de ar que não possam ser bloqueadas; ' },
  { id: 271, label: '13.5.2.2 d) iluminação nos termos da legislação vigente;' },
  { id: 272, label: '13.5.2.2 e) sistema de iluminação de emergência, exceto para vasos de pressão móveis que não exijam a presença de um operador para seu funcionamento.' },
  { id: 273, label: '13.5.2.3 Quando o vaso de pressão for instalado em ambiente aberto, a instalação deve satisfazer os requisitos contidos nas alíneas “a”, “b”, “d” e “e” do subitem 13.5.2.2. ' },
  { id: 274, label: '13.5.2.4 A instalação de vasos de pressão deve obedecer aos aspectos de segurança, saúde e meio ambiente previstos nas normas regulamentadoras, convenções e disposições legais aplicáveis.' },
  { id: 275, label: '13.5.2.5 Quando o estabelecimento não puder atender ao disposto no subitem 13.5.2.2ou 13.5.2.3, o empregador deve adotar medidas complementares de segurança, constantes em relatório elaborado por responsável técnico, que permitam a atenuação dos riscos.' },
  { id: 276, label: '13.5.3 Segurança na operação de vasos de pressão' },
  { id: 277, label: '13.5.3.1 Todo vaso de pressão enquadrado nas categorias I ou II deve possuir manual de operação próprio, manual de operação da unidade ou instruções de operação, em língua portuguesa, em local de fácil acesso aos operadores, contendo no mínimo: ' },
  { id: 278, label: '13.5.3.1 a) procedimentos de partidas e paradas;' },
  { id: 279, label: '13.5.3.1 b) procedimentos e parâmetros operacionais de rotina;' },
  { id: 280, label: '13.5.3.1 c) procedimentos para situações de emergência; ' },
  { id: 281, label: '13.5.3.1 d) procedimentos gerais de segurança, saúde e de preservação do meio ambiente' },
  { id: 282, label: '13.5.3.2 A operação de unidade(s) de processo que possuam vasos de pressão de categorias I ou II deve ser efetuada por profissional capacitado, conforme item 2.1 do Anexo I desta NR.' },
  { id: 283, label: '13.5.4 Inspeção de segurança de vasos de pressão.' },
  { id: 284, label: '13.5.4.1 Os vasos de pressão devem ser submetidos a inspeções de segurança inicial, periódica e extraordinária.' },
  { id: 285, label: '13.5.4.2 A inspeção de segurança inicial deve ser feita em vasos de pressão novos, antes de sua entrada em funcionamento, no local definitivo de instalação, devendo compreender exames externo e interno. ' },
  { id: 286, label: '13.5.4.3 Os vasos de pressão devem, obrigatoriamente, ser submetidos a TH em sua fase de fabricação, com comprovação por meio de laudo assinado por responsável técnico designado pelo fabricante ou importador. ' },
  { id: 287, label: '13.5.4.3.1 Na falta de comprovação documental de que o TH tenha sido realizado na fase de fabricação, se aplicará o disposto a seguir: ' },
  { id: 288, label: '13.5.4.3.1 a) para os vasos de pressão fabricados ou importados a partir de 2 de maio de 2014, o TH deve ser feito durante a inspeção inicial;' },
  { id: 289, label: '13.5.4.3.1 b) para os vasos de pressão em operação antes de 02 de maio de 2014, a execução do TH correspondente ao da fase de fabricação fica a critério técnico do PLH e, caso este julgue necessário, deve ser executado até a próxima inspeção de segurança periódica interna.' },
  { id: 290, label: '13.5.4.4 Os vasos de pressão categorias IV ou V de produção seriada, certificados por Organismo de Certificação de Produto - OCP, acreditado pelo INMETRO, ficam dispensados da inspeção inicial, desde que instalados de acordo com as recomendações do fabricante.' },
  { id: 291, label: '13.5.4.4.1 Deve ser anotada no registro de segurança a data da instalação do vaso de pressão, a partir da qual se inicia a contagem do prazo para a inspeção de segurança periódica.' },
  { id: 292, label: '13.5.4.5 A inspeção de segurança periódica, constituída por exames externo e interno, deve obedecer aos prazos máximos indicados na Tabela 2, com base na categoria do vaso:' },
  { id: 293, label: '13.5.4.5.1 Os estabelecimentos que possuam SPIE certificado poderão ampliar os prazos disciplinados na Tabela 2, nos casos de implementação de metodologia documentada de inspeção baseada em risco, observado o limite máximo de 10 (dez) anos para o exame interno de vasos categoria I.' },
  { id: 294, label: '13.5.4.5.2 A metodologia a que alude o item anterior deve ser integrada ao Programa de Gerenciamento de Riscos - PGR, nos termos da NR-01, com a definição dos critérios, das normas de referência e dos responsáveis pela sua implementação e aprovação. ' },
  { id: 295, label: '13.5.4.5.3 A inspeção periódica interna dos vasos de pressão poderá ser postergada, pela metade do prazo fixado na Tabela 2, mediante o atendimento dos seguintes requisitos:' },
  { id: 296, label: '13.5.4.5.3 a) empresas que possuam SPIE, conforme Anexo II desta NR;' },
  { id: 297, label: '13.5.4.5.3 b) avaliação de risco aprovada por PLH, assegurada a participação dos responsáveis pela operação do equipamento;' },
  { id: 298, label: '13.5.4.5.3 c) definição dos parâmetros operacionais e dos instrumentos de controle essenciais ao monitoramento do equipamento;' },
  { id: 299, label: '13.5.4.5.3 d) implementação de metodologia documentada de Inspeção Não Intrusiva - INI, observado o disposto na ABNT NBR 16455 ou alteração posterior;' },
  { id: 300, label: '13.5.4.5.3 e) emissão de relatório de inspeção, com a definição da data improrrogável da próxima inspeção periódica interna;' },
  { id: 301, label: '13.5.4.5.3 f) anuência do empregador ou de preposto por ele designado.' },
  { id: 302, label: '13.5.4.5.4 O empregador deve comunicar à representação sindical da categoria profissional predominante do estabelecimento, quando formalmente solicitado, a implementação dos novos prazos de inspeção de segurança em face da aplicação das metodologias definidas nos subitens 13.5.4.5.1 e 13.5.4.5.3.' },
  { id: 303, label: '13.5.4.6 Vasos de pressão que não permitam acesso visual para o exame interno ou externo por impossibilidade física devem ser submetidos a exames não destrutivos ou a outras metodologias de avaliação de integridade definidas por PLH, considerados os mecanismos de danos previsíveis.' },
  { id: 304, label: '13.5.4.7 Vasos de pressão com enchimento interno ou com catalisador podem ter a periodicidade de exame interno ampliada, de forma a coincidir com a época da substituição de enchimentos ou de catalisador, desde que esta ampliação seja precedida de estudos conduzidos por PLH ou por grupo multidisciplinar por ele coordenado, baseados em códigos ou normas aplicáveis, onde sejam implementadas tecnologias alternativas para a avaliação da sua integridade estrutural.' },
  { id: 305, label: '13.5.4.8 Vasos de pressão com temperatura de operação inferior a zero grau Celsius (0 °C) e que operem em condições nas quais a experiência mostre que não ocorre deterioração devem ser submetidos a exame externo a cada 2 (dois) anos e a exame interno, quando exigido pelo código de construção ou a critério do PLH.' },
  { id: 306, label: '13.5.4.9 As válvulas de segurança dos vasos de pressão devem ser desmontadas, inspecionadas e testadas com prazo adequado à sua manutenção, porém não superior ao previsto para a inspeção de segurança periódica interna dos vasos de pressão por elas protegidos, de acordo com o subitem 13.5.4.5. ' },
  { id: 307, label: '13.5.4.10 A inspeção de segurança extraordinária deve ser feita nas seguintes oportunidades:' },
  { id: 308, label: '13.5.4.10 a) sempre que o vaso de pressão for danificado por acidente ou outra ocorrência que comprometa sua segurança;' },
  { id: 309, label: '13.5.4.10 b) quando o vaso de pressão for submetido a reparo ou alterações importantes, capazes de alterar sua condição de segurança;' },
  { id: 310, label: '13.5.4.10 c) antes de o vaso de pressão ser recolocado em funcionamento, quando permanecer inativo por mais de 12 (doze) meses; ' },
  { id: 311, label: '13.5.4.10 d) quando houver alteração do local de instalação do vaso de pressão, exceto para vasos móveis.' },
  { id: 312, label: '13.5.4.11 O relatório de inspeção de segurança, mencionado na alínea "d" do subitem 13.5.1.5, deve conter no mínimo:' },
  { id: 313, label: '13.5.4.11 a) identificação do vaso de pressão;' },
  { id: 314, label: '13.5.4.11 b) categoria do vaso de pressão;' },
  { id: 315, label: '13.5.4.11 c) fluidos de serviço;' },
  { id: 316, label: '13.5.4.11 d) tipo do vaso de pressão;' },
  { id: 317, label: '13.5.4.11 e) tipo de inspeção executada;' },
  { id: 318, label: '13.5.4.11 f) data de início e término da inspeção;' },
  { id: 319, label: '13.5.4.11 g) descrição das inspeções, exames e testes executados;' },
  { id: 320, label: '13.5.4.11 h) registro fotográfico das anomalias detectadas no exame interno e externo do vaso de pressão;' },
  { id: 321, label: '13.5.4.11 i) resultado das inspeções e intervenções executadas;' },
  { id: 322, label: '13.5.4.11 j) recomendações e providências necessárias;' },
  { id: 323, label: '13.5.4.11 k) parecer conclusivo quanto à integridade do vaso de pressão até a próxima inspeção;' },
  { id: 324, label: '13.5.4.11 l) data prevista para a próxima inspeção de segurança;' },
  { id: 325, label: '13.5.4.11 m)nome legível, assinatura e número do registro no conselho profissional do PLH e nome legível e assinatura de técnicos que participaram da inspeção;' },
  { id: 326, label: '13.5.4.11 n) número do certificado de inspeção e teste da(s) válvula(s) de segurança.' },
  { id: 327, label: '13.5.4.12 Sempre que os resultados da inspeção determinarem alterações das condições de projeto, a placa de identificação e a documentação do prontuário devem ser atualizadas.' },
  { id: 328, label: '' },
  { id: 329, label: '' },
  { id: 330, label: '' },
  { id: 331, label: '' },
  { id: 332, label: '' },
  { id: 333, label: '' },
  { id: 334, label: '' },
  { id: 335, label: '' },
  { id: 336, label: '' },
  { id: 337, label: '' },
  { id: 338, label: '' },
  { id: 339, label: '' },
  { id: 340, label: '' },
  { id: 341, label: '' },
  { id: 342, label: '' },
  { id: 343, label: '' },
  { id: 344, label: '' },
  { id: 345, label: '' },
  { id: 346, label: '' },
  { id: 347, label: '' },
  { id: 348, label: '' },
  { id: 349, label: '' },
  { id: 350, label: '' },
  { id: 351, label: '' },
  { id: 352, label: '' },
  { id: 353, label: '' },
  { id: 354, label: '' },
  { id: 355, label: '' },
  { id: 356, label: '' },
  { id: 357, label: '' },
  { id: 358, label: '' },
  { id: 359, label: '' },
  { id: 360, label: '' },
  { id: 361, label: '' },
  { id: 362, label: '' },
  { id: 363, label: '' },
  { id: 364, label: '' },
  { id: 365, label: '' },
  { id: 366, label: '' },
  { id: 367, label: '' },
  { id: 368, label: '' },
  { id: 369, label: '' },
  { id: 370, label: '' },
  { id: 371, label: '' },
  { id: 372, label: '' },
  { id: 373, label: '' },
  { id: 374, label: '' },
  { id: 375, label: '' },
  { id: 376, label: '' },
  { id: 377, label: '' },
  { id: 378, label: '' },
  { id: 379, label: '' },
  { id: 380, label: '' },
  { id: 381, label: '' },
  { id: 382, label: '' },
];

export default checklistItemsNR13;